### ISSUE TITLE
Finalize Project frontmatter

### ISSUE THREAD

**Issue by mininimal** [mininimal/gmgmgm#13]
Current frontmatter is:
```yaml
---
title: Example project title
workYear: 2000
company: ExampleCorp
description: "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Me non paenitet nullum festiviorem excogitasse ad hoc."
role:
  - Web Design
  - UX Design
  - Product Design
  - Graphic Design
thumb: images/thing.png
featured: false
draft: true
---
```
Some other possible fields:

- [ ] Team (could be an array with name and link)
- [ ] Link for live projects
