### ISSUE TITLE
Finalize Post frontmatter

### ISSUE THREAD

**Issue by mininimal** [mininimal/gmgmgm#4]
Current frontmatter is:
```yaml
---
title: "Example title"
published: 2000-01-01
updated: 2000-01-02
categories:
  - example
draft: true/false
---
```
This is good enough for now, but some changes will probably keep posts more portable for the future.

- [ ] Dates should be in UTC to make life easier when following guides
- [ ] `published` should be the conventional `date`
- [ ] `updated` should be automatically filled with file save date
- [ ] Add unique ID for rss as in #3
