### ISSUE TITLE
Issue Title

### ISSUE THREAD

**Issue by mininimal** [mininimal/gmgmgm#45]
`<h1>` elements in `<section>`s (and a few more elements) are rendered as `<h2>` because of some old af [HTML standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#specify_font-size_and_margin-block_on_h1). Add the below to `reset.css` to avoid:

```css
:where(h1) {
  margin-block: 0.67em;
  font-size: 2em;
}
```
